# Generated by Django 4.2 on 2026-03-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_teachers_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Приподователь', 'verbose_name_plural': 'Преподователи'},
        ),
    ]
