# Generated by Django 4.2 on 2026-03-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(default='h', max_length=100),
        ),
    ]
