# Generated by Django 4.2 on 2026-03-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_teacher_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
