# Generated by Django 4.2 on 2026-03-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_group_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedule'},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='Time',
            new_name='time',
        ),
    ]
